config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'my_registrations' }
  
  # omniauth_callbacks: 'users/omniauth_callbacks' ## Place inside controllers above 
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'posts#index'

  resources :users, only: [:index, :show, :edit, :update] do
    resource :user_information, only: [:edit]
  end

  resources :user_informations, only: [:update]
  resources :friend_invitations, only: [:create]

  resources :posts, only: [:index, :create] do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create]
  end

  resources :comments, only: [:show] do
    resources :likes, only: [:create, :destroy]
  end

  resources :friendships, only: [:show, :create, :update, :destroy]
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :likeable, polymorphic: true
  belongs_to :user

  validates :user_id, uniqueness: { scope: :likeable_id }
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
        @parent = parent
        @like = @parent.likes.build(user_id: current_user.id)
        @like.save

        update_like
    end

    def destroy
        @parent = parent
        @like = @parent.likes.find(params[:id])
        @like.destroy

        update_like
    end

    private

    def parent
        return Post.find(params[:post_id]) if params[:post_id]

        Comment.find(params[:comment_id]) if params[:comment_id]
    end

    def update_like
        @parent ||= parent
        @parent_model = @parent.model_name.to_s.downcase

        render turbo_stream:
            turbo_stream.replace("#{@parent_model}_like_#{@parent.id}",
                partial: "likes/#{@parent_model}_likes",
                locals: { parent: @parent })
    end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_comment_likes.html.erb
<div id=<%= "comment_like_#{parent.id}" %>>
    <% like = parent.likes.find_by(user_id: current_user.id) %>
    <% if like %>
        <%= link_to image_tag("thumb_up", alt: "Like Post"), comment_like_path(parent, like), data: { "turbo-method": :delete } %>
    <% else %>
        <%= link_to image_tag("thumb_up", alt: "Like Post"), comment_likes_path(parent), data: { "turbo-method": :post } %>
    <% end %>
    <div class="likes-count"><%= parent.likes.count.to_s %></div>
</div>

app/views/likes/_like_counter.html.erb
<div id=<%= "counter_#{post.id}" %>>
    <% if post.likes.find_by(user_id: current_user.id) %>
        <%= link_to image_tag("thumb_up", alt: "Like Post"), post_like_path(post, current_user), data: { "turbo-method": :delete } %>
    <% else %>
        <%= link_to image_tag("thumb_up", alt: "Like Post"), post_likes_path(post), data: { "turbo-method": :post } %>
    <% end %>
    <div class="likes-count"><%= post.likes.count.to_s %></div>
</div>

<!--<%= link_to image_tag("thumb_up", alt: "Like Post"), post_likes_path(post), data: { "turbo-method": :post } %>-->

app/views/likes/_post_likes.html.erb
<div id=<%= "post_like_#{parent.id}" %>>
    <% like = parent.likes.find_by(user_id: current_user.id) %>
    <% if like %>
        <%= link_to image_tag("thumb_up", alt: "Like Post"), post_like_path(parent, like), data: { "turbo-method": :delete } %>
    <% else %>
        <%= link_to image_tag("thumb_up", alt: "Like Post"), post_likes_path(parent), data: { "turbo-method": :post } %>
    <% end %>
    <div class="likes-count"><%= parent.likes.count.to_s %></div>
</div>