config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'my_registrations' }
  
  # omniauth_callbacks: 'users/omniauth_callbacks' ## Place inside controllers above 
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'posts#index'

  resources :users, only: [:index, :show, :edit, :update] do
    resource :user_information, only: [:edit]
  end

  resources :user_informations, only: [:update]
  resources :friend_invitations, only: [:create]

  resources :posts, only: [:index, :create] do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create]
  end

  resources :comments, only: [:show] do
    resources :likes, only: [:create, :destroy]
  end

  resources :friendships, only: [:show, :create, :update, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  devise :omniauthable, omniauth_providers: %i[facebook]

  has_many :friendships, dependent: :destroy
  has_many :friends, through: :friendships

  has_many :sent_invitations, class_name: 'FriendInvitation', foreign_key: :sender_id, dependent: :destroy
  has_many :received_invitations, class_name: 'FriendInvitation', foreign_key: :receiver_id

  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_one :user_information, dependent: :destroy
  accepts_nested_attributes_for :user_information

  has_one_attached :profile_picture

  scope :not_friends, ->(current_user) { where.not(id: Friendship.where(user_id: current_user).uniq.pluck(:friend_id).push(current_user)) }

  def self.from_omniauth(auth)
    find_or_create_by(provider: auth.provider, uid: auth.uid) do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.user_information.first_name = auth.info.first_name
      user.user_information.last_name = auth.info.last_name
      # If you are using confirmable and the provider(s) you use validate emails,
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def friend_invitations_count
    received_invitations.count.to_s
  end

  def display_name
    "#{user_information.first_name} #{user_information.last_name}"
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
    # See https://github.com/omniauth/omniauth/wiki/FAQ#rails-session-is-clobbered-after-callback-on-developer-strategy
    skip_before_action :verify_authenticity_token, only: :facebook
  
    def facebook
      # You need to implement the method below in your model (e.g. app/models/user.rb)
      @user = User.from_omniauth(request.env["omniauth.auth"])
  
      if @user.persisted?
        sign_in_and_redirect @user, event: :authentication # this will throw if @user is not activated
        set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
      else
        session["devise.facebook_data"] = request.env["omniauth.auth"].except(:extra) # Removing extra as it can overflow some session stores
        redirect_to new_user_registration_url
      end
    end
  
    def failure
      redirect_to root_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!

    def index
        @users = User.not_friends(current_user.id).includes(:user_information, :received_invitations)
    end

    def show
        @user = User.includes(:user_information).find(params[:id])
        @posts = Post.where(user_id: @user.id).includes(:likes, user: :user_information, comments: { user: :user_information }, image_attachment: :blob).limit(10)
    end

    def edit
        @user = User.find(current_user.id)
    end

    def update
        @user = User.find(current_user.id)
        @user.profile_picture.attach(params[:user][:profile_picture]) unless params[:user].nil?

        if @user.save
            redirect_to user_path(@user)
        else
            render :edit
        end
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<turbo-frame id="profile-picture-frame">
    <% if current_user.profile_picture.attached? %>
        <%= image_tag(@user.profile_picture, alt: "Profile") %>
    <% else %>
        <%= image_tag("profile_icon", alt: "Profile") %>
    <% end %>

    <%= form_with model: @user, multipart: true do |form| %>
        <%= form.file_field :profile_picture %>

        <%= form.submit "Update Profile Picture", data: { turbo_frame: "_top" } %>
    <% end %>
</turbo-frame>

app/views/users/index.html.erb
<div class="invitations-container">
    <div class="label">Friend Invitations</div>
    <% @users.each do |user| %>
        <div class="invitation">
            <%= user.display_name %>

            
            <% if user.received_invitations.where(sender_id: current_user.id).any? %> 
                <%= content_tag(:div, "Invitation Sent") %>
            <% else %>
                <%= link_to "Send Invite", friend_invitations_path(recipient: user.id), data: { 'turbo-method': :post } %>
            <% end %>
        </div>
    <% end %>
</div>

app/views/users/show.html.erb
<div class="user-information-container">
    <turbo-frame id="profile-picture-frame">
        <% if @user.id == current_user.id %>
            <div class="img-text">Click Me</div>
            <% if @user.profile_picture.attached? %>
                <%= link_to image_tag(@user.profile_picture, alt: "Profile"), edit_user_path(@user) %>
            <% else %>
                <%= link_to image_tag("profile_icon", alt: "Profile"), edit_user_path(@user) %>
            <% end %>
        <% else %>
             <% if @user.profile_picture.attached? %>
                <%= image_tag(@user.profile_picture, alt: "Profile") %>
            <% else %>
                <%= image_tag("profile_icon", alt: "Profile") %>
            <% end %>
        <% end %>
    </turbo-frame>

    <turbo-frame id="user-information-frame">
        <div class="inner-information">
            <% if @user.id == current_user.id %>
                <%= link_to "Edit", edit_user_user_information_path(@user) %>
            <% end %>
            <div class="information">
                <div>Email:</div>
                <div><%= @user.email %></div>
            </div>
            <div class="information">
                <div>First Name:</div>
                <div><%= @user.user_information.first_name %></div>
            </div>
            <div class="information">
                <div>Last Name:</div>
                <div><%= @user.user_information.last_name %></div>
            </div>
        </div>
    </turbo-frame>
</div>
    
<div class="posts-container user-posts-container">
    <% if @posts.empty? %>
        <div class="header">No Posts :(</div>
    <% end %>
    <% @posts.each do |post| %>
        <div class="post">
            <%= render "posts/post", post: post %>
        </div>
    <% end %>
</div>