config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'my_registrations' }
  
  # omniauth_callbacks: 'users/omniauth_callbacks' ## Place inside controllers above 
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'posts#index'

  resources :users, only: [:index, :show, :edit, :update] do
    resource :user_information, only: [:edit]
  end

  resources :user_informations, only: [:update]
  resources :friend_invitations, only: [:create]

  resources :posts, only: [:index, :create] do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create]
  end

  resources :comments, only: [:show] do
    resources :likes, only: [:create, :destroy]
  end

  resources :friendships, only: [:show, :create, :update, :destroy]
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  validates :user_id, uniqueness: { scope: :friend_id }

  belongs_to :user
  belongs_to :friend, class_name: 'User'

  def self.create_friendship(users)
    @first_connection = Friendship.find_or_create_by(user_id: users[:current_user], friend_id: users[:friend])
    @second_connection = Friendship.find_or_create_by(user_id: users[:friend], friend_id: users[:current_user])

    @first_connection && @second_connection ? true : false
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
    before_action :authenticate_user!

    def show
        @active_friendships = current_user.friendships.includes(friend: :user_information)
        @pending_invitations = current_user.received_invitations.includes(sender: :user_information)
    end

    def create
        @friendship = Friendship.create_friendship({ current_user: current_user.id, friend: params[:friend_id] })

        if @friendship
            FriendInvitation.destroy_invitation({ invitation: params[:invitation_id] })
            flash[:notice] = 'Friend added'
        else
            flash[:alert] = 'Friend not added'
        end

        redirect_back(fallback_location: root_path)
    end
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/views/friendships/show.html.erb
<div class="active-friends">
    <div>My Friends</div>
    <ul>
        <% @active_friendships.each do |friendship| %>
            <li><%= friendship.friend.display_name %></li>
        <% end %>
    </ul>
</div>

<div class="pending-invitations">
    <div>Pending Friend Invitations</div>
    <% @pending_invitations.each do |invitation| %>
        <div class="pending-container">
            <%= invitation.sender.display_name %>
            <%= link_to "Accept Invititation", friendships_path(friend_id: invitation.sender.id, invitation_id: invitation.id), data: {'turbo-method': :post} %>
        </div>
    <% end %>
</div>
    